-- =====================================================
-- V075: Create SaaS Gateway Configuration Table
-- =====================================================
-- Stores payment gateway configuration for receiving
-- payments from workshops (used by SUPER_ADMIN only).
-- =====================================================

CREATE TABLE IF NOT EXISTS configuracao_gateway (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Gateway type (MERCADO_PAGO, etc.)
    tipo VARCHAR(30) NOT NULL UNIQUE,

    -- Status
    ativo BOOLEAN NOT NULL DEFAULT FALSE,
    sandbox BOOLEAN NOT NULL DEFAULT TRUE,

    -- Mercado Pago credentials
    access_token VARCHAR(500),
    public_key VARCHAR(200),
    webhook_secret VARCHAR(200),

    -- Webhook URL (generated by system)
    webhook_url VARCHAR(500),

    -- Validation info
    ultima_validacao TIMESTAMP,
    validacao_sucesso BOOLEAN,
    mensagem_validacao VARCHAR(500),

    -- Audit
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by UUID,

    CONSTRAINT fk_configuracao_gateway_updated_by
        FOREIGN KEY (updated_by) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_configuracao_gateway_tipo ON configuracao_gateway(tipo);
CREATE INDEX IF NOT EXISTS idx_configuracao_gateway_ativo ON configuracao_gateway(ativo);

-- Comments
COMMENT ON TABLE configuracao_gateway IS 'SaaS payment gateway configuration for receiving payments from workshops';
COMMENT ON COLUMN configuracao_gateway.tipo IS 'Gateway type: MERCADO_PAGO, etc.';
COMMENT ON COLUMN configuracao_gateway.ativo IS 'Whether this gateway is active for receiving payments';
COMMENT ON COLUMN configuracao_gateway.sandbox IS 'Whether to use sandbox/test mode';
COMMENT ON COLUMN configuracao_gateway.access_token IS 'API access token (encrypted in production)';
COMMENT ON COLUMN configuracao_gateway.public_key IS 'Public key for frontend integrations';
COMMENT ON COLUMN configuracao_gateway.webhook_secret IS 'Secret for webhook signature validation';
