package com.pitstop.saas.domain;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Entity to store payment gateway configuration for SaaS.
 * Only SUPER_ADMIN can manage this configuration.
 *
 * The access token and secrets are encrypted before storage.
 */
@Entity(name = "SaasConfiguracaoGateway")
@Table(name = "saas_configuracao_gateway")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ConfiguracaoGateway {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private TipoGateway tipo;

    @Column(nullable = false)
    @Builder.Default
    private Boolean ativo = false;

    @Column(nullable = false)
    @Builder.Default
    private Boolean sandbox = true;

    // Mercado Pago credentials
    @Column(name = "access_token", length = 500)
    private String accessToken;

    @Column(name = "public_key", length = 200)
    private String publicKey;

    @Column(name = "webhook_secret", length = 200)
    private String webhookSecret;

    // Webhook URL (read-only, generated by system)
    @Column(name = "webhook_url", length = 500)
    private String webhookUrl;

    // Last validation
    @Column(name = "ultima_validacao")
    private LocalDateTime ultimaValidacao;

    @Column(name = "validacao_sucesso")
    private Boolean validacaoSucesso;

    @Column(name = "mensagem_validacao", length = 500)
    private String mensagemValidacao;

    // Audit
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Column(name = "updated_by")
    private UUID updatedBy;

    // =====================================
    // BUSINESS METHODS
    // =====================================

    /**
     * Check if gateway is ready to process payments.
     */
    public boolean isConfigurado() {
        return ativo && accessToken != null && !accessToken.isBlank();
    }

    /**
     * Mark validation result.
     */
    public void marcarValidacao(boolean sucesso, String mensagem) {
        this.ultimaValidacao = LocalDateTime.now();
        this.validacaoSucesso = sucesso;
        this.mensagemValidacao = mensagem;
    }

    /**
     * Mask access token for display (show only last 4 chars).
     */
    public String getAccessTokenMasked() {
        if (accessToken == null || accessToken.length() < 8) {
            return "****";
        }
        return "****" + accessToken.substring(accessToken.length() - 4);
    }

    /**
     * Mask public key for display.
     */
    public String getPublicKeyMasked() {
        if (publicKey == null || publicKey.length() < 8) {
            return "****";
        }
        return "****" + publicKey.substring(publicKey.length() - 4);
    }
}
